AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'LambdaLayers

  Sample SAM Template for LambdaLayers

  '
Globals:
  Function:
    Timeout: 5
Resources:
  Service1Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://vashi-lambda-code/fedd37a74bf7686de53cb15f7fcd19f4
      Handler: service1.lambda_handler
      Runtime: python3.7
      Layers:
      - Ref: CustomCodeLayer
  Service2Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://vashi-lambda-code/fedd37a74bf7686de53cb15f7fcd19f4
      Handler: service2.lambda_handler
      Runtime: python3.7
      Layers:
      - Ref: CustomCodeLayer
  CustomCodeLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: CustomCodeLayer
      Description: Layer with customer code
      ContentUri: s3://vashi-lambda-code/47a398f1434d13c19466d6e7e3678765
      CompatibleRuntimes:
      - python3.7
      LicenseInfo: Available under the MIT-0 license.
      RetentionPolicy: Retain
